#!/usr/bin/env node
/**
 * Fetches trending entries from githubawesome.com and creates a weekly GitHub issue.
 * Closes the previous week's issue before creating a new one.
 *
 * Uses:
 * - Jina Reader (free, no auth) to fetch and convert githubawesome.com to text
 * - GitHub Issues API (uses GITHUB_TOKEN) to manage issues
 */

const TODAY = new Date().toISOString().split("T")[0];
const GITHUB_API = "https://api.github.com";
const AWESOME_URL = "https://githubawesome.com/";
const ISSUE_LABEL = "github-awesome";

function githubHeaders() {
  return {
    Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
    "Content-Type": "application/json",
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
  };
}

async function fetchAwesomeEntries() {
  const jinaUrl = `https://r.jina.ai/${AWESOME_URL}`;
  const res = await fetch(jinaUrl, {
    headers: {
      Accept: "text/plain",
      "X-Return-Format": "text",
      "User-Agent": "agents-core/github-awesome-bot",
    },
    signal: AbortSignal.timeout(30000),
  });
  if (!res.ok)
    throw new Error(`Failed to fetch githubawesome.com: ${res.status}`);

  const text = await res.text();
  return parseEntries(text);
}

function parseEntries(text) {
  const entries = [];
  // Match markdown-style links with descriptions: [Title](url) — description
  // or lines like: **Title** - description \n url
  const lines = text.split("\n");

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue;

    // Pattern: [repo or title](https://github.com/...) optional description
    const linkMatch = line.match(
      /\[([^\]]+)\]\((https:\/\/github\.com\/[^\s)]+)\)\s*[-–—:]?\s*(.*)/
    );
    if (linkMatch) {
      entries.push({
        name: linkMatch[1].trim(),
        url: linkMatch[2].trim(),
        summary: linkMatch[3].trim() || "",
      });
      continue;
    }

    // Pattern: https://github.com/owner/repo with surrounding text
    const urlMatch = line.match(/(https:\/\/github\.com\/[\w.-]+\/[\w.-]+)/);
    if (urlMatch) {
      const url = urlMatch[1];
      const rest = line.replace(url, "").replace(/[-–—|:*#]/g, "").trim();
      if (rest) {
        entries.push({
          name: url.split("/").slice(-2).join("/"),
          url,
          summary: rest,
        });
      }
    }
  }

  // Deduplicate by URL
  const seen = new Set();
  return entries.filter((e) => {
    if (seen.has(e.url)) return false;
    seen.add(e.url);
    return true;
  });
}

function buildIssueBody(entries) {
  let md = `> Weekly snapshot from [githubawesome.com](${AWESOME_URL}) — ${TODAY}\n\n`;

  if (entries.length === 0) {
    md += `_No entries could be parsed this week. Check the [site](${AWESOME_URL}) directly._\n`;
  } else {
    md += `| # | Repository | Summary |\n`;
    md += `|---|------------|--------|\n`;

    for (let i = 0; i < entries.length; i++) {
      const e = entries[i];
      const repoLink = `[${e.name}](${e.url})`;
      const summary = e.summary || "—";
      md += `| ${i + 1} | ${repoLink} | ${summary} |\n`;
    }
  }

  md += `\n---\n`;
  md += `*Auto-generated by the [GitHub Awesome workflow](../../actions/workflows/github-awesome.yml).*\n`;
  md += `\nBrowse all entries: ${AWESOME_URL}`;
  return md;
}

async function closePreviousIssues() {
  const url = `${GITHUB_API}/repos/${process.env.GITHUB_REPOSITORY}/issues?labels=${ISSUE_LABEL}&state=open&per_page=100`;
  const res = await fetch(url, { headers: githubHeaders() });
  if (!res.ok) return 0;

  const issues = await res.json();
  let closed = 0;

  for (const issue of issues) {
    const patchRes = await fetch(
      `${GITHUB_API}/repos/${process.env.GITHUB_REPOSITORY}/issues/${issue.number}`,
      {
        method: "PATCH",
        headers: githubHeaders(),
        body: JSON.stringify({ state: "closed", state_reason: "completed" }),
      }
    );
    if (patchRes.ok) {
      console.log(`  Closed previous issue #${issue.number}: ${issue.title}`);
      closed++;
    }
  }

  return closed;
}

async function createIssue(title, body) {
  const res = await fetch(
    `${GITHUB_API}/repos/${process.env.GITHUB_REPOSITORY}/issues`,
    {
      method: "POST",
      headers: githubHeaders(),
      body: JSON.stringify({ title, body, labels: [ISSUE_LABEL] }),
    }
  );
  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Failed to create issue: ${err}`);
  }
  return res.json();
}

async function main() {
  for (const env of ["GITHUB_TOKEN", "GITHUB_REPOSITORY"]) {
    if (!process.env[env]) throw new Error(`Missing required env var: ${env}`);
  }

  console.log(`GitHub Awesome Snapshot — ${TODAY}`);

  // Close previous week's issues
  console.log("\nClosing previous github-awesome issues...");
  const closed = await closePreviousIssues();
  console.log(`  Closed ${closed} previous issue(s).`);

  // Fetch and parse entries
  console.log("\nFetching githubawesome.com...");
  const entries = await fetchAwesomeEntries();
  console.log(`  Parsed ${entries.length} entries`);

  for (const e of entries.slice(0, 10)) {
    console.log(`  - ${e.name}: ${e.summary || "(no summary)"}`);
  }

  // Create new issue
  const title = `GitHub Awesome — ${TODAY}`;
  const body = buildIssueBody(entries);
  const issue = await createIssue(title, body);
  console.log(`\nCreated issue #${issue.number}: ${title}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
