#!/usr/bin/env node
/**
 * Fetches the top 10 skills from skills.sh and creates a weekly GitHub issue.
 * Closes the previous week's skills issue before creating a new one.
 *
 * Uses:
 * - Direct fetch of skills.sh HTML to extract embedded JSON from Next.js RSC payload
 * - GitHub Issues API (uses GITHUB_TOKEN) to manage issues
 */

const TODAY = new Date().toISOString().split("T")[0];
const GITHUB_API = "https://api.github.com";
const SKILLS_URL = "https://skills.sh";
const ISSUE_LABEL = "top-skills";

function githubHeaders() {
  return {
    Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
    "Content-Type": "application/json",
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
  };
}

async function fetchTopSkills(count = 10) {
  const res = await fetch(SKILLS_URL, {
    headers: { "User-Agent": "agents-core/top-skills-bot" },
    signal: AbortSignal.timeout(20000),
  });
  if (!res.ok) throw new Error(`Failed to fetch skills.sh: ${res.status}`);

  const html = await res.text();

  // skills.sh is a Next.js app that embeds leaderboard data in RSC script payloads
  // Format: self.__next_f.push([1,"..."]) with JSON-escaped content containing initialSkills
  const scripts = html.match(/self\.__next_f\.push\(\[1,"(.*?)"\]\)/gs);
  if (!scripts) throw new Error("No Next.js RSC payloads found in skills.sh HTML");

  for (const script of scripts) {
    if (!script.includes("initialSkills")) continue;

    const inner = script.match(/self\.__next_f\.push\(\[1,"(.*)"\]\)/s);
    if (!inner) continue;

    // Unescape the double-encoded JSON string
    const parsed = JSON.parse(`"${inner[1]}"`);
    const dataMatch = parsed.match(/"initialSkills":(\[\{.*?\}\])/);
    if (!dataMatch) continue;

    const skills = JSON.parse(dataMatch[1]);
    return skills.slice(0, count).map((item, i) => ({
      rank: i + 1,
      name: item.name || item.skillId,
      repo: item.source,
      installs: item.installs,
    }));
  }

  throw new Error("Could not find initialSkills data in skills.sh HTML");
}

function formatInstalls(n) {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return String(n);
}

function buildIssueBody(skills) {
  let md = `> Weekly snapshot from [skills.sh](https://skills.sh) — ${TODAY}\n\n`;
  md += `| Rank | Skill | Repository | Installs |\n`;
  md += `|------|-------|------------|----------|\n`;

  for (const s of skills) {
    const repoLink = `[${s.repo}](https://github.com/${s.repo})`;
    md += `| ${s.rank} | ${s.name} | ${repoLink} | ${formatInstalls(s.installs)} |\n`;
  }

  md += `\n---\n`;
  md += `*Auto-generated by the [Top Skills workflow](../../actions/workflows/top-skills.yml).*\n`;
  md += `\nInstall any skill: \`npx skills add <owner/repo>\``;
  return md;
}

async function closePreviousIssues() {
  const url = `${GITHUB_API}/repos/${process.env.GITHUB_REPOSITORY}/issues?labels=${ISSUE_LABEL}&state=open&per_page=100`;
  const res = await fetch(url, { headers: githubHeaders() });
  if (!res.ok) return 0;

  const issues = await res.json();
  let closed = 0;

  for (const issue of issues) {
    const patchRes = await fetch(
      `${GITHUB_API}/repos/${process.env.GITHUB_REPOSITORY}/issues/${issue.number}`,
      {
        method: "PATCH",
        headers: githubHeaders(),
        body: JSON.stringify({ state: "closed", state_reason: "completed" }),
      }
    );
    if (patchRes.ok) {
      console.log(`  Closed previous issue #${issue.number}: ${issue.title}`);
      closed++;
    }
  }

  return closed;
}

async function createIssue(title, body) {
  const res = await fetch(
    `${GITHUB_API}/repos/${process.env.GITHUB_REPOSITORY}/issues`,
    {
      method: "POST",
      headers: githubHeaders(),
      body: JSON.stringify({ title, body, labels: [ISSUE_LABEL] }),
    }
  );
  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Failed to create issue: ${err}`);
  }
  return res.json();
}

async function main() {
  for (const env of ["GITHUB_TOKEN", "GITHUB_REPOSITORY"]) {
    if (!process.env[env]) throw new Error(`Missing required env var: ${env}`);
  }

  console.log(`Top Skills Snapshot — ${TODAY}`);

  // Close previous week's issues
  console.log("\nClosing previous top-skills issues...");
  const closed = await closePreviousIssues();
  console.log(`  Closed ${closed} previous issue(s).`);

  // Fetch and parse skills
  console.log("\nFetching skills.sh...");
  const skills = await fetchTopSkills();
  console.log(`  Parsed ${skills.length} skills`);

  for (const s of skills) {
    console.log(`  #${s.rank} ${s.name} (${s.repo}) — ${formatInstalls(s.installs)}`);
  }

  // Create new issue
  const title = `Top 10 Agent Skills — ${TODAY}`;
  const body = buildIssueBody(skills);
  const issue = await createIssue(title, body);
  console.log(`\nCreated issue #${issue.number}: ${title}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
